- name: Create zabbix Repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ zabbix_repo }}"
  
- name: Install zabbix Agent
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-agent

- name: Configure to Accept access from others postgresql.conf
  lineinfile:
    path: "/etc/zabbix/zabbix_agentd.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: '^Server = ', line: "Server =  {{ zabbix_server_ip }}"}
    - {regexp: '^ServerActive = ', line: "ServerActive = {{ zabbix_server_ip }}"}
    - {regexp: '^HostMetadata = ', line: "HostMetadata = {{zabbix_metadata}}:{{ group_names }}"}
    - {regexp: '^hostname = ', line: "hostname =  {{ inventory_hostname }}"}